#!/usr/bin/env python3
"""Regenerate projects/README.md (the master project index) from the
per-project markdown files under projects/{active,shipped,parked,shelved}/.

WHY THIS EXISTS: gtd/projects.md rotted because nothing kept it current.
Here the per-project files are the SOURCE OF TRUTH (hand-curated), and this
script rebuilds the index from their frontmatter — so the index can never
drift from the files. Re-run it whenever you add or change a project file.

Usage:
    python scripts/projects_index.py           # rebuild projects/README.md
    python scripts/projects_index.py --check    # print what it would write, don't save
"""
import os
import sys
import glob
import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJ = os.path.join(ROOT, "projects")
BUCKETS = ["active", "shipped", "parked", "shelved"]
BUCKET_TITLES = {
    "active": "Active — in flight now",
    "shipped": "Shipped / Reference — built, kept for reference",
    "parked": "Parked — paused, may resume",
    "shelved": "Shelved — ready but not firing, or killed",
}
# Curated display order for areas; anything not listed sorts alphabetically after.
AREA_ORDER = [
    "Cool Hollow Coaching",
    "Content",
    "Creative",
    "Platform & Web",
    "Business & Admin",
]


def parse_frontmatter(text):
    """Tolerant YAML-subset parser: scalars `key: value` and one list `sources:`."""
    if not text.startswith("---"):
        return {}
    lines = text.splitlines()
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        return {}
    fm = {}
    current_key = None
    for ln in lines[1:end]:
        if not ln.strip():
            continue
        stripped = ln.lstrip()
        if stripped.startswith("- ") and current_key == "sources":
            fm.setdefault("sources", []).append(stripped[2:].strip())
            continue
        if ":" in ln:
            k, _, v = ln.partition(":")
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            current_key = k
            if k == "sources":
                fm["sources"] = []
                if v:
                    fm["sources"].append(v)
            else:
                fm[k] = v
    return fm


def load():
    items = []
    for bucket in BUCKETS:
        d = os.path.join(PROJ, bucket)
        if not os.path.isdir(d):
            continue
        for path in sorted(glob.glob(os.path.join(d, "*.md"))):
            with open(path, encoding="utf-8") as f:
                fm = parse_frontmatter(f.read())
            fm["_bucket"] = bucket
            fm["_path"] = os.path.relpath(path, PROJ)
            fm.setdefault("name", os.path.basename(path)[:-3])
            fm.setdefault("area", "Uncategorised")
            items.append(fm)
    return items


def area_key(area):
    return (AREA_ORDER.index(area) if area in AREA_ORDER else len(AREA_ORDER), area)


def prio_key(item):
    p = item.get("priority", "")
    try:
        return (0, int(p))
    except (ValueError, TypeError):
        return (1, 0)


def build():
    items = load()
    out = ["# Projects — Master Index", ""]
    today = datetime.date.today().isoformat()
    counts = {b: sum(1 for it in items if it["_bucket"] == b) for b in BUCKETS}
    out.append(
        f"_Auto-generated by `scripts/projects_index.py` on {today}. "
        "The per-project files in the folders below are the source of truth — "
        "edit those, then re-run the script. Do not hand-edit this file._"
    )
    out.append("")
    summ = " · ".join(f"{counts[b]} {b}" for b in BUCKETS if counts[b])
    out.append(f"**{len(items)} projects** — {summ}.")
    out.append("")
    for bucket in BUCKETS:
        bucket_items = [it for it in items if it["_bucket"] == bucket]
        if not bucket_items:
            continue
        out.append(f"## {BUCKET_TITLES[bucket]}")
        out.append("")
        for area in sorted({it["area"] for it in bucket_items}, key=area_key):
            area_items = sorted(
                [it for it in bucket_items if it["area"] == area], key=prio_key
            )
            out.append(f"### {area}")
            out.append("")
            for it in area_items:
                la = it.get("last_activity", "")
                pr = it.get("priority", "")
                meta = f" · {la}" if la else ""
                prtag = f" · P{pr}" if pr else ""
                out.append(f"- **[{it.get('name')}]({it['_path']})**{meta}{prtag}")
                if it.get("summary"):
                    out.append(f"  {it['summary']}")
                na = it.get("next_action", "")
                if na and na.lower() not in ("none", "n/a", "-", ""):
                    out.append(f"  **Next:** {na}")
            out.append("")
    return "\n".join(out).rstrip() + "\n", counts, len(items)


def main():
    text, counts, total = build()
    if "--check" in sys.argv:
        print(text)
        return
    os.makedirs(PROJ, exist_ok=True)
    with open(os.path.join(PROJ, "README.md"), "w", encoding="utf-8") as f:
        f.write(text)
    print(f"Wrote projects/README.md — {total} projects ({counts}).")


if __name__ == "__main__":
    main()
